/* The following code was generated by JFlex 1.3.5 on 4/2/20, 11:50 PM */

package cup.p1;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;

/* Custom Imports */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 4/2/20, 11:50 PM from the specification file
 * <tt>file:/home/dumont_dev/work/ws/java/universidad/pl/git/PL-P1/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\22\1\2\1\0\1\22\1\1\16\0\4\0\1\22\1\7"+
    "\2\0\1\0\3\0\1\32\1\33\1\5\1\15\1\0\1\10\1\12"+
    "\1\4\1\17\1\30\2\27\6\3\1\0\1\31\1\6\1\0\1\11"+
    "\1\0\1\25\4\16\1\14\1\16\21\26\1\21\2\26\4\0\1\0"+
    "\1\0\4\24\1\13\22\24\1\20\2\24\4\0\41\0\2\0\4\0"+
    "\4\0\1\0\2\0\1\0\7\0\1\0\4\0\1\0\5\0\1\0"+
    "\1\23\7\0\1\23\3\0\1\23\3\0\1\23\1\0\1\23\3\0"+
    "\1\0\2\0\1\23\6\0\1\24\7\0\1\24\3\0\1\24\3\0"+
    "\1\24\1\0\1\24\3\0\1\0\2\0\1\24\u01c7\0\4\0\14\0"+
    "\16\0\5\0\7\0\1\0\1\0\1\0\21\0\160\0\5\0\1\0"+
    "\2\0\2\0\4\0\1\0\1\0\6\0\1\0\1\0\3\0\1\0"+
    "\1\0\1\0\24\0\1\0\123\0\1\0\213\0\1\0\5\0\2\0"+
    "\246\0\1\0\46\0\2\0\1\0\7\0\47\0\7\0\1\0\1\0"+
    "\55\0\1\0\1\0\1\0\2\0\1\0\2\0\1\0\1\0\10\0"+
    "\33\0\5\0\3\0\15\0\6\0\5\0\1\0\4\0\13\0\1\0"+
    "\1\0\3\0\53\0\37\0\4\0\2\0\1\0\143\0\1\0\1\0"+
    "\10\0\1\0\6\0\2\0\2\0\1\0\4\0\2\0\12\0\3\0"+
    "\2\0\1\0\17\0\1\0\1\0\1\0\36\0\33\0\2\0\131\0"+
    "\13\0\1\0\16\0\12\0\41\0\11\0\2\0\4\0\1\0\5\0"+
    "\26\0\4\0\1\0\11\0\1\0\3\0\1\0\5\0\22\0\31\0"+
    "\3\0\4\0\13\0\65\0\25\0\1\0\10\0\26\0\60\0\66\0"+
    "\3\0\1\0\22\0\1\0\7\0\12\0\2\0\2\0\12\0\1\0"+
    "\20\0\3\0\1\0\10\0\2\0\2\0\2\0\26\0\1\0\7\0"+
    "\1\0\1\0\3\0\4\0\2\0\1\0\1\0\7\0\2\0\2\0"+
    "\2\0\3\0\1\0\10\0\1\0\4\0\2\0\1\0\3\0\2\0"+
    "\2\0\12\0\4\0\7\0\2\0\4\0\3\0\1\0\6\0\4\0"+
    "\2\0\2\0\26\0\1\0\7\0\1\0\2\0\1\0\2\0\1\0"+
    "\2\0\2\0\1\0\1\0\5\0\4\0\2\0\2\0\3\0\3\0"+
    "\1\0\7\0\4\0\1\0\1\0\7\0\14\0\3\0\1\0\13\0"+
    "\3\0\1\0\11\0\1\0\3\0\1\0\26\0\1\0\7\0\1\0"+
    "\2\0\1\0\5\0\2\0\1\0\1\0\10\0\1\0\3\0\1\0"+
    "\3\0\2\0\1\0\17\0\2\0\2\0\2\0\12\0\1\0\1\0"+
    "\7\0\1\0\6\0\1\0\3\0\1\0\10\0\2\0\2\0\2\0"+
    "\26\0\1\0\7\0\1\0\2\0\1\0\5\0\2\0\1\0\1\0"+
    "\7\0\2\0\2\0\2\0\3\0\10\0\2\0\4\0\2\0\1\0"+
    "\3\0\2\0\2\0\12\0\1\0\1\0\20\0\1\0\1\0\1\0"+
    "\6\0\3\0\3\0\1\0\4\0\3\0\2\0\1\0\1\0\1\0"+
    "\2\0\3\0\2\0\3\0\3\0\3\0\14\0\4\0\5\0\3\0"+
    "\3\0\1\0\4\0\2\0\1\0\6\0\1\0\16\0\12\0\11\0"+
    "\1\0\6\0\4\0\1\0\10\0\1\0\3\0\1\0\27\0\1\0"+
    "\20\0\3\0\1\0\7\0\1\0\3\0\1\0\4\0\7\0\2\0"+
    "\1\0\3\0\5\0\2\0\2\0\2\0\12\0\20\0\1\0\3\0"+
    "\1\0\10\0\1\0\3\0\1\0\27\0\1\0\12\0\1\0\5\0"+
    "\2\0\1\0\1\0\7\0\1\0\3\0\1\0\4\0\7\0\2\0"+
    "\7\0\1\0\1\0\2\0\2\0\2\0\12\0\1\0\2\0\15\0"+
    "\4\0\1\0\10\0\1\0\3\0\1\0\51\0\2\0\1\0\7\0"+
    "\1\0\3\0\1\0\4\0\1\0\5\0\3\0\1\0\7\0\3\0"+
    "\2\0\2\0\12\0\12\0\6\0\2\0\2\0\1\0\22\0\3\0"+
    "\30\0\1\0\11\0\1\0\1\0\2\0\7\0\3\0\1\0\4\0"+
    "\6\0\1\0\1\0\1\0\10\0\6\0\12\0\2\0\2\0\15\0"+
    "\60\0\1\0\2\0\7\0\4\0\10\0\10\0\1\0\12\0\47\0"+
    "\2\0\1\0\1\0\2\0\2\0\1\0\1\0\2\0\1\0\6\0"+
    "\4\0\1\0\7\0\1\0\3\0\1\0\1\0\1\0\1\0\2\0"+
    "\2\0\1\0\4\0\1\0\2\0\6\0\1\0\2\0\1\0\2\0"+
    "\5\0\1\0\1\0\1\0\6\0\2\0\12\0\2\0\4\0\40\0"+
    "\1\0\27\0\2\0\6\0\12\0\13\0\1\0\1\0\1\0\1\0"+
    "\1\0\4\0\2\0\10\0\1\0\44\0\4\0\24\0\1\0\2\0"+
    "\5\0\13\0\1\0\44\0\11\0\1\0\71\0\53\0\24\0\1\0"+
    "\12\0\6\0\6\0\4\0\4\0\3\0\1\0\3\0\2\0\7\0"+
    "\3\0\4\0\15\0\14\0\1\0\17\0\2\0\46\0\1\0\1\0"+
    "\5\0\1\0\2\0\53\0\1\0\u014d\0\1\0\4\0\2\0\7\0"+
    "\1\0\1\0\1\0\4\0\2\0\51\0\1\0\4\0\2\0\41\0"+
    "\1\0\4\0\2\0\7\0\1\0\1\0\1\0\4\0\2\0\17\0"+
    "\1\0\71\0\1\0\4\0\2\0\103\0\2\0\3\0\40\0\20\0"+
    "\20\0\126\0\2\0\6\0\3\0\u026c\0\2\0\21\0\1\0\32\0"+
    "\5\0\113\0\3\0\13\0\7\0\15\0\1\0\4\0\3\0\13\0"+
    "\22\0\3\0\13\0\22\0\2\0\14\0\15\0\1\0\3\0\1\0"+
    "\2\0\14\0\64\0\40\0\3\0\1\0\3\0\2\0\1\0\2\0"+
    "\12\0\41\0\4\0\1\0\12\0\6\0\130\0\10\0\5\0\2\0"+
    "\42\0\1\0\1\0\5\0\106\0\12\0\37\0\1\0\14\0\4\0"+
    "\14\0\12\0\12\0\36\0\2\0\5\0\13\0\54\0\4\0\32\0"+
    "\6\0\12\0\46\0\27\0\5\0\4\0\65\0\12\0\1\0\35\0"+
    "\2\0\13\0\6\0\12\0\15\0\1\0\10\0\16\0\102\0\5\0"+
    "\57\0\21\0\7\0\4\0\12\0\21\0\11\0\14\0\3\0\36\0"+
    "\15\0\2\0\12\0\54\0\16\0\14\0\44\0\24\0\10\0\12\0"+
    "\3\0\3\0\12\0\44\0\2\0\11\0\107\0\3\0\1\0\25\0"+
    "\4\0\1\0\4\0\3\0\2\0\3\0\6\0\300\0\72\0\1\0"+
    "\5\0\u0116\0\2\0\6\0\2\0\46\0\2\0\6\0\2\0\10\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\0\1\0\37\0\2\0\65\0"+
    "\1\0\7\0\1\0\1\0\3\0\3\0\1\0\7\0\3\0\4\0"+
    "\2\0\6\0\4\0\15\0\5\0\3\0\1\0\7\0\16\0\5\0"+
    "\32\0\5\0\20\0\2\0\23\0\1\0\13\0\5\0\1\0\12\0"+
    "\1\0\1\0\15\0\1\0\20\0\15\0\3\0\40\0\20\0\15\0"+
    "\4\0\1\0\3\0\14\0\21\0\1\0\4\0\1\0\2\0\12\0"+
    "\1\0\1\0\3\0\5\0\6\0\1\0\1\0\1\0\1\0\1\0"+
    "\1\0\4\0\1\0\13\0\2\0\4\0\5\0\5\0\4\0\1\0"+
    "\21\0\51\0\u0a77\0\57\0\1\0\57\0\1\0\205\0\6\0\4\0"+
    "\3\0\2\0\14\0\46\0\1\0\1\0\5\0\1\0\2\0\70\0"+
    "\7\0\1\0\17\0\1\0\27\0\11\0\7\0\1\0\7\0\1\0"+
    "\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0"+
    "\7\0\1\0\40\0\57\0\1\0\u01d5\0\3\0\31\0\11\0\6\0"+
    "\1\0\5\0\2\0\5\0\4\0\126\0\2\0\2\0\2\0\3\0"+
    "\1\0\132\0\1\0\4\0\5\0\52\0\2\0\136\0\21\0\33\0"+
    "\65\0\20\0\u0200\0\u19b6\0\112\0\u51eb\0\25\0\u048d\0\103\0\56\0"+
    "\2\0\u010d\0\3\0\20\0\12\0\2\0\24\0\57\0\1\0\4\0"+
    "\12\0\1\0\37\0\2\0\120\0\2\0\45\0\11\0\2\0\147\0"+
    "\2\0\44\0\1\0\10\0\77\0\13\0\1\0\3\0\1\0\4\0"+
    "\1\0\27\0\5\0\20\0\1\0\7\0\64\0\14\0\2\0\62\0"+
    "\22\0\12\0\12\0\6\0\22\0\6\0\3\0\1\0\1\0\1\0"+
    "\2\0\12\0\34\0\10\0\2\0\27\0\15\0\14\0\35\0\3\0"+
    "\4\0\57\0\16\0\16\0\1\0\12\0\6\0\5\0\1\0\12\0"+
    "\12\0\5\0\1\0\51\0\16\0\11\0\3\0\1\0\10\0\2\0"+
    "\2\0\12\0\6\0\27\0\3\0\1\0\3\0\62\0\1\0\1\0"+
    "\3\0\2\0\2\0\5\0\2\0\1\0\1\0\1\0\30\0\3\0"+
    "\2\0\13\0\5\0\2\0\3\0\2\0\12\0\6\0\2\0\6\0"+
    "\2\0\6\0\11\0\7\0\1\0\7\0\1\0\53\0\1\0\12\0"+
    "\12\0\163\0\10\0\1\0\2\0\2\0\12\0\6\0\u2ba4\0\14\0"+
    "\27\0\4\0\61\0\u2104\0\u016e\0\2\0\152\0\46\0\7\0\14\0"+
    "\5\0\5\0\1\0\1\0\12\0\1\0\15\0\1\0\5\0\1\0"+
    "\1\0\1\0\2\0\1\0\2\0\1\0\154\0\41\0\u016b\0\22\0"+
    "\100\0\2\0\66\0\50\0\15\0\3\0\20\0\20\0\20\0\3\0"+
    "\2\0\30\0\3\0\31\0\1\0\6\0\5\0\1\0\207\0\2\0"+
    "\1\0\4\0\1\0\13\0\12\0\7\0\32\0\4\0\1\0\1\0"+
    "\32\0\13\0\131\0\3\0\6\0\2\0\6\0\2\0\6\0\2\0"+
    "\3\0\3\0\2\0\3\0\2\0\22\0\3\0\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    28,    56,    84,   112,   140,   168,    56,   196,    56, 
      224,    56,   252,    56,   280,   308,    56,    56,    56,   112, 
       56,   336,   364,   392,   420,   448,   476,   504,   532,   560, 
      588,   616,   644,   672,   700,   728,   756,   784,   812,   840, 
      868,   868,   896,   112,   924,   952,   980,  1008,  1036,  1064, 
     1092,   700,  1120,  1148,  1176,  1204,  1232,  1260,    56,  1288, 
     1316,  1344,  1372,  1400,  1120,  1428,  1456,  1484,  1512,  1540, 
     1568,  1596,   728,  1624,  1652,  1680,  1708,  1736,  1764,  1792, 
     1820,  1568,  1848,  1596,  1876,  1904,  1932,  1960,  1988,    56, 
     2016,  2044,  2072,  1120,  2100,  1344,  2128,  2156,  1512,  2184, 
     2212,   448,    56,    56,  1624,  2128,  2240,  1960,  2268,  2296, 
     2128
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\3\3\1\13\1\14\1\13\1\15\1\3\1\13"+
    "\1\16\1\17\2\3\1\13\2\20\1\21\1\22\1\23"+
    "\34\24\2\25\1\0\22\25\1\26\10\25\1\5\22\25"+
    "\1\26\6\25\34\0\2\25\1\0\1\27\1\30\5\25"+
    "\1\31\2\32\2\25\1\27\5\25\1\26\1\25\2\27"+
    "\5\25\1\0\1\25\1\33\1\34\17\25\1\26\10\25"+
    "\1\0\4\25\1\35\15\25\1\26\10\25\1\0\1\36"+
    "\4\25\1\37\2\25\1\17\1\40\1\25\1\40\1\36"+
    "\1\17\1\40\1\41\2\17\1\26\1\40\2\36\5\25"+
    "\1\0\1\42\1\30\5\25\1\31\2\32\2\25\1\42"+
    "\2\43\3\25\1\26\1\25\2\42\5\25\1\0\10\25"+
    "\2\17\1\25\1\17\1\25\2\17\1\41\2\17\1\26"+
    "\1\17\7\25\1\0\1\42\1\30\5\25\1\31\2\32"+
    "\2\25\1\42\5\25\1\26\1\25\2\42\3\25\2\44"+
    "\1\0\31\44\2\25\1\0\1\45\6\25\1\31\2\32"+
    "\2\25\1\45\5\25\1\26\1\25\2\45\5\25\1\0"+
    "\1\46\13\25\1\47\5\25\1\26\1\25\1\46\1\47"+
    "\5\25\1\0\1\50\13\25\1\50\5\25\1\26\1\25"+
    "\2\50\5\25\1\0\1\51\4\25\1\52\4\25\1\52"+
    "\1\25\1\51\5\25\1\26\1\25\2\51\3\25\1\33"+
    "\1\53\1\54\22\33\1\55\6\33\2\34\1\56\2\34"+
    "\1\57\17\34\1\60\6\34\2\25\1\0\5\25\1\61"+
    "\14\25\1\26\10\25\1\0\1\62\13\25\1\62\5\25"+
    "\1\26\1\25\2\62\5\25\1\0\1\63\13\25\1\63"+
    "\5\25\1\26\1\25\2\63\5\25\1\0\1\36\4\25"+
    "\1\37\2\25\2\17\1\25\1\17\1\36\2\17\1\41"+
    "\2\17\1\26\1\17\2\36\5\25\1\0\11\25\1\17"+
    "\1\25\1\17\2\25\1\17\1\41\1\17\1\25\1\26"+
    "\1\17\7\25\1\0\1\45\1\30\5\25\1\31\2\32"+
    "\2\25\1\45\5\25\1\26\1\25\2\45\5\25\1\0"+
    "\1\64\10\25\1\64\1\25\2\64\5\25\1\26\1\25"+
    "\2\64\3\25\2\44\1\0\7\44\1\65\21\44\2\25"+
    "\1\0\1\66\6\25\1\31\2\32\2\25\1\66\5\25"+
    "\1\26\1\25\2\66\5\25\1\0\1\25\1\67\20\25"+
    "\1\26\10\25\1\0\1\46\1\67\12\25\1\46\5\25"+
    "\1\26\1\25\2\46\5\25\1\0\1\50\7\25\2\32"+
    "\2\25\1\50\5\25\1\26\1\25\2\50\5\25\1\0"+
    "\1\51\13\25\1\51\5\25\1\26\1\25\2\51\5\25"+
    "\1\54\22\25\1\26\6\25\1\70\1\71\1\54\31\70"+
    "\5\56\1\72\26\56\2\34\1\56\1\34\1\73\1\57"+
    "\17\34\1\60\6\34\2\74\1\56\2\74\1\75\26\74"+
    "\2\25\1\0\5\25\1\76\14\25\1\26\10\25\1\0"+
    "\1\77\13\25\1\77\5\25\1\26\1\25\2\77\5\25"+
    "\1\0\1\100\13\25\1\100\5\25\1\26\1\25\2\100"+
    "\3\25\2\101\1\0\31\101\2\25\1\0\1\102\4\25"+
    "\1\103\1\25\1\31\1\32\1\104\1\25\1\105\1\102"+
    "\1\25\1\105\3\25\1\26\1\105\2\102\5\25\1\0"+
    "\1\106\13\25\1\106\5\25\1\26\1\25\2\106\3\25"+
    "\1\70\1\71\1\54\7\70\1\107\21\70\2\44\1\54"+
    "\7\44\1\65\21\44\4\56\1\54\1\72\26\56\2\74"+
    "\1\56\2\74\1\75\4\74\1\110\23\74\1\56\1\74"+
    "\1\111\1\75\4\74\1\110\21\74\2\76\1\112\5\76"+
    "\1\113\14\76\1\114\6\76\2\25\1\0\1\115\13\25"+
    "\1\115\5\25\1\26\1\25\2\115\5\25\1\0\1\116"+
    "\13\25\1\116\5\25\1\26\1\25\2\116\5\25\1\0"+
    "\1\117\6\25\1\31\2\32\2\25\1\117\5\25\1\26"+
    "\1\25\2\117\5\25\1\0\11\25\1\105\1\25\1\105"+
    "\2\25\1\105\3\25\1\26\1\105\7\25\1\0\1\51"+
    "\4\25\1\52\3\25\1\120\1\52\1\120\1\51\1\25"+
    "\1\120\3\25\1\26\1\120\2\51\5\25\1\0\11\25"+
    "\1\120\1\25\1\120\2\25\1\120\3\25\1\26\1\120"+
    "\7\25\1\0\1\121\13\25\1\121\5\25\1\26\1\25"+
    "\2\121\3\25\1\122\1\123\1\54\31\122\2\124\1\56"+
    "\2\124\1\125\26\124\10\112\1\126\23\112\2\76\1\112"+
    "\5\76\1\127\14\76\1\114\6\76\2\130\1\112\5\130"+
    "\1\131\23\130\2\25\1\0\1\132\10\25\1\120\1\25"+
    "\1\120\1\132\1\25\1\120\3\25\1\26\1\120\2\132"+
    "\5\25\1\0\1\133\13\25\1\133\5\25\1\26\1\25"+
    "\2\133\5\25\1\0\1\134\6\25\1\31\2\32\2\25"+
    "\1\134\5\25\1\26\1\25\2\134\5\25\1\0\11\25"+
    "\1\132\1\25\1\132\2\25\1\132\3\25\1\26\1\132"+
    "\7\25\1\0\1\135\13\25\1\135\5\25\1\26\1\25"+
    "\2\135\3\25\2\101\1\54\31\101\2\124\1\56\1\124"+
    "\1\136\1\125\26\124\10\112\1\137\23\112\2\76\1\112"+
    "\5\76\1\127\1\140\13\76\1\114\6\76\2\130\1\112"+
    "\5\130\1\131\1\130\1\141\23\130\1\112\5\130\1\142"+
    "\1\130\1\141\21\130\2\25\1\0\1\132\4\25\1\143"+
    "\6\25\1\132\5\25\1\26\1\25\2\132\5\25\1\0"+
    "\1\144\4\25\1\145\1\25\1\31\1\32\1\146\1\25"+
    "\1\147\1\144\1\25\1\147\3\25\1\26\1\147\2\144"+
    "\5\25\1\0\1\150\13\25\1\150\5\25\1\26\1\25"+
    "\2\150\3\25\10\112\1\137\1\151\22\112\2\152\1\112"+
    "\5\152\1\153\23\152\2\130\1\112\5\130\1\142\1\154"+
    "\1\141\21\130\2\25\1\0\1\155\4\25\1\145\1\25"+
    "\1\31\1\32\1\146\1\25\1\147\1\155\1\25\1\147"+
    "\3\25\1\26\1\147\2\155\5\25\1\0\11\25\1\147"+
    "\1\25\1\147\2\25\1\147\3\25\1\26\1\147\5\25"+
    "\2\152\1\112\5\152\1\156\23\152\2\25\1\0\1\155"+
    "\6\25\1\31\2\32\2\25\1\155\5\25\1\26\1\25"+
    "\2\155\3\25\2\152\1\112\5\152\1\156\1\157\22\152";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  9,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1, 
     1,  1,  0,  0,  1,  0,  0,  1,  1,  0,  1,  9,  0,  0,  0,  0, 
     0,  0,  0,  1,  0,  1,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0, 
     1,  1,  0,  1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  1, 
     0,  1,  1,  1,  1,  0,  0,  0,  0,  1,  0,  1,  0,  1,  0,  1, 
     0,  0,  0,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2324];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2296) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 51: 
          {  return symbolFactory.newSymbol("HEXNUMBER", HEXNUMBER, Integer.parseInt(yytext().substring(2,yytext().length()), 16));  }
        case 112: break;
        case 11: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 113: break;
        case 16: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 114: break;
        case 6: 
          {  return symbolFactory.newSymbol("DIVIDEDBY", DIVIDEDBY);  }
        case 115: break;
        case 39: 
        case 40: 
          {  return symbolFactory.newSymbol("DOUBLENUMBER", DOUBLENUMBER, Double.parseDouble(yytext()));  }
        case 116: break;
        case 42: 
        case 43: 
        case 56: 
        case 58: 
        case 72: 
        case 82: 
        case 93: 
        case 95: 
        case 104: 
        case 107: 
        case 110: 
          {  return symbolFactory.newSymbol("COMMENT", COMMENT, yytext());  }
        case 117: break;
        case 17: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 118: break;
        case 18: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 119: break;
        case 5: 
        case 12: 
        case 15: 
        case 22: 
        case 33: 
        case 36: 
        case 53: 
        case 65: 
        case 78: 
        case 91: 
        case 99: 
        case 108: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext()));  }
        case 120: break;
        case 3: 
        case 4: 
        case 13: 
          {                                }
        case 121: break;
        case 67: 
        case 68: 
        case 79: 
        case 89: 
          {  return symbolFactory.newSymbol("MATRICULA", MATRICULA, yytext());  }
        case 122: break;
        case 9: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 123: break;
        case 7: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 124: break;
        case 2: 
        case 8: 
        case 19: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 125: break;
        case 10: 
        case 14: 
        case 31: 
        case 32: 
          {  return symbolFactory.newSymbol("NOMBREAPELLIDOS", NOMBREAPELLIDOS, yytext());  }
        case 126: break;
        case 103: 
          {  return symbolFactory.newSymbol("FECHA", FECHA, yytext());  }
        case 127: break;
        case 64: 
        case 81: 
        case 83: 
        case 84: 
        case 105: 
        case 106: 
        case 109: 
          {  return symbolFactory.newSymbol("EMAIL", EMAIL, yytext());  }
        case 128: break;
        case 101: 
        case 102: 
          {  return symbolFactory.newSymbol("DNI", DNI, yytext());  }
        case 129: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
