/* The following code was generated by JFlex 1.3.5 on 4/3/20, 12:04 AM */

package cup.p1;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;

/* Custom Imports */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 4/3/20, 12:04 AM from the specification file
 * <tt>file:/home/dumont_dev/work/ws/java/universidad/pl/git/PL-P1/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\22\1\2\1\0\1\22\1\1\16\0\4\0\1\22\1\7"+
    "\2\0\1\0\3\0\1\32\1\37\1\5\1\15\1\0\1\10\1\12"+
    "\1\4\1\17\1\30\2\27\6\3\1\0\1\36\1\6\1\0\1\11"+
    "\1\0\1\25\4\16\1\14\1\16\21\26\1\21\2\26\4\0\1\0"+
    "\1\0\4\24\1\13\1\24\1\35\4\24\1\33\2\24\1\34\1\31"+
    "\7\24\1\20\2\24\4\0\41\0\2\0\4\0\4\0\1\0\2\0"+
    "\1\0\7\0\1\0\4\0\1\0\5\0\1\0\1\23\7\0\1\23"+
    "\3\0\1\23\3\0\1\23\1\0\1\23\3\0\1\0\2\0\1\23"+
    "\6\0\1\24\7\0\1\24\3\0\1\24\3\0\1\24\1\0\1\24"+
    "\3\0\1\0\2\0\1\24\u01c7\0\4\0\14\0\16\0\5\0\7\0"+
    "\1\0\1\0\1\0\21\0\160\0\5\0\1\0\2\0\2\0\4\0"+
    "\1\0\1\0\6\0\1\0\1\0\3\0\1\0\1\0\1\0\24\0"+
    "\1\0\123\0\1\0\213\0\1\0\5\0\2\0\246\0\1\0\46\0"+
    "\2\0\1\0\7\0\47\0\7\0\1\0\1\0\55\0\1\0\1\0"+
    "\1\0\2\0\1\0\2\0\1\0\1\0\10\0\33\0\5\0\3\0"+
    "\15\0\6\0\5\0\1\0\4\0\13\0\1\0\1\0\3\0\53\0"+
    "\37\0\4\0\2\0\1\0\143\0\1\0\1\0\10\0\1\0\6\0"+
    "\2\0\2\0\1\0\4\0\2\0\12\0\3\0\2\0\1\0\17\0"+
    "\1\0\1\0\1\0\36\0\33\0\2\0\131\0\13\0\1\0\16\0"+
    "\12\0\41\0\11\0\2\0\4\0\1\0\5\0\26\0\4\0\1\0"+
    "\11\0\1\0\3\0\1\0\5\0\22\0\31\0\3\0\4\0\13\0"+
    "\65\0\25\0\1\0\10\0\26\0\60\0\66\0\3\0\1\0\22\0"+
    "\1\0\7\0\12\0\2\0\2\0\12\0\1\0\20\0\3\0\1\0"+
    "\10\0\2\0\2\0\2\0\26\0\1\0\7\0\1\0\1\0\3\0"+
    "\4\0\2\0\1\0\1\0\7\0\2\0\2\0\2\0\3\0\1\0"+
    "\10\0\1\0\4\0\2\0\1\0\3\0\2\0\2\0\12\0\4\0"+
    "\7\0\2\0\4\0\3\0\1\0\6\0\4\0\2\0\2\0\26\0"+
    "\1\0\7\0\1\0\2\0\1\0\2\0\1\0\2\0\2\0\1\0"+
    "\1\0\5\0\4\0\2\0\2\0\3\0\3\0\1\0\7\0\4\0"+
    "\1\0\1\0\7\0\14\0\3\0\1\0\13\0\3\0\1\0\11\0"+
    "\1\0\3\0\1\0\26\0\1\0\7\0\1\0\2\0\1\0\5\0"+
    "\2\0\1\0\1\0\10\0\1\0\3\0\1\0\3\0\2\0\1\0"+
    "\17\0\2\0\2\0\2\0\12\0\1\0\1\0\7\0\1\0\6\0"+
    "\1\0\3\0\1\0\10\0\2\0\2\0\2\0\26\0\1\0\7\0"+
    "\1\0\2\0\1\0\5\0\2\0\1\0\1\0\7\0\2\0\2\0"+
    "\2\0\3\0\10\0\2\0\4\0\2\0\1\0\3\0\2\0\2\0"+
    "\12\0\1\0\1\0\20\0\1\0\1\0\1\0\6\0\3\0\3\0"+
    "\1\0\4\0\3\0\2\0\1\0\1\0\1\0\2\0\3\0\2\0"+
    "\3\0\3\0\3\0\14\0\4\0\5\0\3\0\3\0\1\0\4\0"+
    "\2\0\1\0\6\0\1\0\16\0\12\0\11\0\1\0\6\0\4\0"+
    "\1\0\10\0\1\0\3\0\1\0\27\0\1\0\20\0\3\0\1\0"+
    "\7\0\1\0\3\0\1\0\4\0\7\0\2\0\1\0\3\0\5\0"+
    "\2\0\2\0\2\0\12\0\20\0\1\0\3\0\1\0\10\0\1\0"+
    "\3\0\1\0\27\0\1\0\12\0\1\0\5\0\2\0\1\0\1\0"+
    "\7\0\1\0\3\0\1\0\4\0\7\0\2\0\7\0\1\0\1\0"+
    "\2\0\2\0\2\0\12\0\1\0\2\0\15\0\4\0\1\0\10\0"+
    "\1\0\3\0\1\0\51\0\2\0\1\0\7\0\1\0\3\0\1\0"+
    "\4\0\1\0\5\0\3\0\1\0\7\0\3\0\2\0\2\0\12\0"+
    "\12\0\6\0\2\0\2\0\1\0\22\0\3\0\30\0\1\0\11\0"+
    "\1\0\1\0\2\0\7\0\3\0\1\0\4\0\6\0\1\0\1\0"+
    "\1\0\10\0\6\0\12\0\2\0\2\0\15\0\60\0\1\0\2\0"+
    "\7\0\4\0\10\0\10\0\1\0\12\0\47\0\2\0\1\0\1\0"+
    "\2\0\2\0\1\0\1\0\2\0\1\0\6\0\4\0\1\0\7\0"+
    "\1\0\3\0\1\0\1\0\1\0\1\0\2\0\2\0\1\0\4\0"+
    "\1\0\2\0\6\0\1\0\2\0\1\0\2\0\5\0\1\0\1\0"+
    "\1\0\6\0\2\0\12\0\2\0\4\0\40\0\1\0\27\0\2\0"+
    "\6\0\12\0\13\0\1\0\1\0\1\0\1\0\1\0\4\0\2\0"+
    "\10\0\1\0\44\0\4\0\24\0\1\0\2\0\5\0\13\0\1\0"+
    "\44\0\11\0\1\0\71\0\53\0\24\0\1\0\12\0\6\0\6\0"+
    "\4\0\4\0\3\0\1\0\3\0\2\0\7\0\3\0\4\0\15\0"+
    "\14\0\1\0\17\0\2\0\46\0\1\0\1\0\5\0\1\0\2\0"+
    "\53\0\1\0\u014d\0\1\0\4\0\2\0\7\0\1\0\1\0\1\0"+
    "\4\0\2\0\51\0\1\0\4\0\2\0\41\0\1\0\4\0\2\0"+
    "\7\0\1\0\1\0\1\0\4\0\2\0\17\0\1\0\71\0\1\0"+
    "\4\0\2\0\103\0\2\0\3\0\40\0\20\0\20\0\126\0\2\0"+
    "\6\0\3\0\u026c\0\2\0\21\0\1\0\32\0\5\0\113\0\3\0"+
    "\13\0\7\0\15\0\1\0\4\0\3\0\13\0\22\0\3\0\13\0"+
    "\22\0\2\0\14\0\15\0\1\0\3\0\1\0\2\0\14\0\64\0"+
    "\40\0\3\0\1\0\3\0\2\0\1\0\2\0\12\0\41\0\4\0"+
    "\1\0\12\0\6\0\130\0\10\0\5\0\2\0\42\0\1\0\1\0"+
    "\5\0\106\0\12\0\37\0\1\0\14\0\4\0\14\0\12\0\12\0"+
    "\36\0\2\0\5\0\13\0\54\0\4\0\32\0\6\0\12\0\46\0"+
    "\27\0\5\0\4\0\65\0\12\0\1\0\35\0\2\0\13\0\6\0"+
    "\12\0\15\0\1\0\10\0\16\0\102\0\5\0\57\0\21\0\7\0"+
    "\4\0\12\0\21\0\11\0\14\0\3\0\36\0\15\0\2\0\12\0"+
    "\54\0\16\0\14\0\44\0\24\0\10\0\12\0\3\0\3\0\12\0"+
    "\44\0\2\0\11\0\107\0\3\0\1\0\25\0\4\0\1\0\4\0"+
    "\3\0\2\0\3\0\6\0\300\0\72\0\1\0\5\0\u0116\0\2\0"+
    "\6\0\2\0\46\0\2\0\6\0\2\0\10\0\1\0\1\0\1\0"+
    "\1\0\1\0\1\0\1\0\37\0\2\0\65\0\1\0\7\0\1\0"+
    "\1\0\3\0\3\0\1\0\7\0\3\0\4\0\2\0\6\0\4\0"+
    "\15\0\5\0\3\0\1\0\7\0\16\0\5\0\32\0\5\0\20\0"+
    "\2\0\23\0\1\0\13\0\5\0\1\0\12\0\1\0\1\0\15\0"+
    "\1\0\20\0\15\0\3\0\40\0\20\0\15\0\4\0\1\0\3\0"+
    "\14\0\21\0\1\0\4\0\1\0\2\0\12\0\1\0\1\0\3\0"+
    "\5\0\6\0\1\0\1\0\1\0\1\0\1\0\1\0\4\0\1\0"+
    "\13\0\2\0\4\0\5\0\5\0\4\0\1\0\21\0\51\0\u0a77\0"+
    "\57\0\1\0\57\0\1\0\205\0\6\0\4\0\3\0\2\0\14\0"+
    "\46\0\1\0\1\0\5\0\1\0\2\0\70\0\7\0\1\0\17\0"+
    "\1\0\27\0\11\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0"+
    "\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0\40\0"+
    "\57\0\1\0\u01d5\0\3\0\31\0\11\0\6\0\1\0\5\0\2\0"+
    "\5\0\4\0\126\0\2\0\2\0\2\0\3\0\1\0\132\0\1\0"+
    "\4\0\5\0\52\0\2\0\136\0\21\0\33\0\65\0\20\0\u0200\0"+
    "\u19b6\0\112\0\u51eb\0\25\0\u048d\0\103\0\56\0\2\0\u010d\0\3\0"+
    "\20\0\12\0\2\0\24\0\57\0\1\0\4\0\12\0\1\0\37\0"+
    "\2\0\120\0\2\0\45\0\11\0\2\0\147\0\2\0\44\0\1\0"+
    "\10\0\77\0\13\0\1\0\3\0\1\0\4\0\1\0\27\0\5\0"+
    "\20\0\1\0\7\0\64\0\14\0\2\0\62\0\22\0\12\0\12\0"+
    "\6\0\22\0\6\0\3\0\1\0\1\0\1\0\2\0\12\0\34\0"+
    "\10\0\2\0\27\0\15\0\14\0\35\0\3\0\4\0\57\0\16\0"+
    "\16\0\1\0\12\0\6\0\5\0\1\0\12\0\12\0\5\0\1\0"+
    "\51\0\16\0\11\0\3\0\1\0\10\0\2\0\2\0\12\0\6\0"+
    "\27\0\3\0\1\0\3\0\62\0\1\0\1\0\3\0\2\0\2\0"+
    "\5\0\2\0\1\0\1\0\1\0\30\0\3\0\2\0\13\0\5\0"+
    "\2\0\3\0\2\0\12\0\6\0\2\0\6\0\2\0\6\0\11\0"+
    "\7\0\1\0\7\0\1\0\53\0\1\0\12\0\12\0\163\0\10\0"+
    "\1\0\2\0\2\0\12\0\6\0\u2ba4\0\14\0\27\0\4\0\61\0"+
    "\u2104\0\u016e\0\2\0\152\0\46\0\7\0\14\0\5\0\5\0\1\0"+
    "\1\0\12\0\1\0\15\0\1\0\5\0\1\0\1\0\1\0\2\0"+
    "\1\0\2\0\1\0\154\0\41\0\u016b\0\22\0\100\0\2\0\66\0"+
    "\50\0\15\0\3\0\20\0\20\0\20\0\3\0\2\0\30\0\3\0"+
    "\31\0\1\0\6\0\5\0\1\0\207\0\2\0\1\0\4\0\1\0"+
    "\13\0\12\0\7\0\32\0\4\0\1\0\1\0\32\0\13\0\131\0"+
    "\3\0\6\0\2\0\6\0\2\0\6\0\2\0\3\0\3\0\2\0"+
    "\3\0\2\0\22\0\3\0\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    32,    64,    96,   128,   160,   192,    64,   224,    64, 
      256,   288,    64,   320,    64,   352,   384,    64,   416,    64, 
       64,   128,    64,   448,   480,   512,   544,   576,   608,   640, 
      672,   704,   736,   768,   800,   832,   864,   896,   928,   960, 
      992,  1024,  1056,  1088,  1120,  1120,  1152,   128,  1184,  1216, 
     1248,  1280,  1312,  1344,  1376,  1408,   896,  1440,  1472,  1504, 
     1536,  1568,  1600,  1632,    64,  1664,  1696,  1728,    64,  1760, 
     1792,    64,  1472,  1824,  1856,  1888,  1920,  1952,  1984,  2016, 
      960,  2048,  2080,  2112,  2144,  2176,  2208,  2240,  2272,  1984, 
     2304,  2016,  2336,  2368,  2400,  2432,  2464,    64,  2496,  2528, 
     2560,  1472,  2592,  1728,  2624,  2656,  1920,  2688,  2720,   576, 
       64,    64,  2048,  2624,  2752,  2432,  2784,  2816,  2624
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\2\3\1\13\1\14\1\15\1\14\1\16\1\3"+
    "\1\14\1\17\1\20\2\3\1\14\2\21\1\3\1\22"+
    "\1\23\2\3\1\24\1\25\40\26\2\27\1\0\22\27"+
    "\1\30\14\27\1\5\22\27\1\30\12\27\40\0\2\27"+
    "\1\0\1\31\1\32\5\27\1\33\2\34\2\27\1\31"+
    "\5\27\1\30\1\27\2\31\11\27\1\0\1\27\1\35"+
    "\1\36\17\27\1\30\14\27\1\0\4\27\1\37\15\27"+
    "\1\30\14\27\1\0\15\27\1\40\4\27\1\30\14\27"+
    "\1\0\1\41\4\27\1\42\2\27\1\20\1\43\1\27"+
    "\1\43\1\41\1\20\1\43\1\44\2\20\1\30\1\43"+
    "\2\41\1\20\1\27\3\20\4\27\1\0\1\45\1\32"+
    "\5\27\1\33\2\34\2\27\1\45\2\46\3\27\1\30"+
    "\1\27\2\45\11\27\1\0\10\27\2\20\1\27\1\20"+
    "\1\27\2\20\1\44\2\20\1\30\1\20\2\27\1\20"+
    "\1\27\3\20\4\27\1\0\1\45\1\32\5\27\1\33"+
    "\2\34\2\27\1\45\5\27\1\30\1\27\2\45\11\27"+
    "\1\0\22\27\1\30\6\27\1\47\3\27\2\50\1\0"+
    "\35\50\2\27\1\0\1\51\6\27\1\33\2\34\2\27"+
    "\1\51\5\27\1\30\1\27\2\51\11\27\1\0\1\52"+
    "\13\27\1\53\5\27\1\30\1\27\1\52\1\53\11\27"+
    "\1\0\1\54\13\27\1\54\5\27\1\30\1\27\2\54"+
    "\11\27\1\0\1\55\4\27\1\56\4\27\1\56\1\27"+
    "\1\55\5\27\1\30\1\27\2\55\7\27\1\35\1\57"+
    "\1\60\22\35\1\61\12\35\2\36\1\62\2\36\1\63"+
    "\17\36\1\64\12\36\2\27\1\0\5\27\1\65\14\27"+
    "\1\30\14\27\1\0\22\27\1\30\3\27\1\66\10\27"+
    "\1\0\1\67\13\27\1\67\5\27\1\30\1\27\2\67"+
    "\11\27\1\0\1\70\13\27\1\70\5\27\1\30\1\27"+
    "\2\70\11\27\1\0\1\41\4\27\1\42\2\27\2\20"+
    "\1\27\1\20\1\41\2\20\1\44\2\20\1\30\1\20"+
    "\2\41\1\20\1\27\3\20\4\27\1\0\11\27\1\20"+
    "\1\27\1\20\2\27\1\20\1\44\1\20\1\27\1\30"+
    "\1\20\13\27\1\0\1\51\1\32\5\27\1\33\2\34"+
    "\2\27\1\51\5\27\1\30\1\27\2\51\11\27\1\0"+
    "\1\71\10\27\1\71\1\27\2\71\5\27\1\30\1\27"+
    "\2\71\11\27\1\0\22\27\1\30\7\27\1\72\2\27"+
    "\2\50\1\0\7\50\1\73\25\50\2\27\1\0\1\74"+
    "\6\27\1\33\2\34\2\27\1\74\5\27\1\30\1\27"+
    "\2\74\11\27\1\0\1\27\1\75\20\27\1\30\14\27"+
    "\1\0\1\52\1\75\12\27\1\52\5\27\1\30\1\27"+
    "\2\52\11\27\1\0\1\54\7\27\2\34\2\27\1\54"+
    "\5\27\1\30\1\27\2\54\11\27\1\0\1\55\13\27"+
    "\1\55\5\27\1\30\1\27\2\55\11\27\1\60\22\27"+
    "\1\30\12\27\1\76\1\77\1\60\35\76\5\62\1\100"+
    "\32\62\2\36\1\62\1\36\1\101\1\63\17\36\1\64"+
    "\12\36\2\102\1\62\2\102\1\103\32\102\2\27\1\0"+
    "\5\27\1\104\14\27\1\30\14\27\1\0\22\27\1\30"+
    "\4\27\1\105\7\27\1\0\1\106\13\27\1\106\5\27"+
    "\1\30\1\27\2\106\11\27\1\0\1\107\13\27\1\107"+
    "\5\27\1\30\1\27\2\107\11\27\1\0\22\27\1\30"+
    "\4\27\1\110\5\27\2\111\1\0\35\111\2\27\1\0"+
    "\1\112\4\27\1\113\1\27\1\33\1\34\1\114\1\27"+
    "\1\115\1\112\1\27\1\115\3\27\1\30\1\115\2\112"+
    "\11\27\1\0\1\116\13\27\1\116\5\27\1\30\1\27"+
    "\2\116\7\27\1\76\1\77\1\60\7\76\1\117\25\76"+
    "\2\50\1\60\7\50\1\73\25\50\4\62\1\60\1\100"+
    "\32\62\2\102\1\62\2\102\1\103\4\102\1\120\27\102"+
    "\1\62\1\102\1\121\1\103\4\102\1\120\25\102\2\104"+
    "\1\122\5\104\1\123\14\104\1\124\12\104\2\27\1\0"+
    "\1\125\13\27\1\125\5\27\1\30\1\27\2\125\11\27"+
    "\1\0\1\126\13\27\1\126\5\27\1\30\1\27\2\126"+
    "\11\27\1\0\1\127\6\27\1\33\2\34\2\27\1\127"+
    "\5\27\1\30\1\27\2\127\11\27\1\0\11\27\1\115"+
    "\1\27\1\115\2\27\1\115\3\27\1\30\1\115\13\27"+
    "\1\0\1\55\4\27\1\56\3\27\1\130\1\56\1\130"+
    "\1\55\1\27\1\130\3\27\1\30\1\130\2\55\11\27"+
    "\1\0\11\27\1\130\1\27\1\130\2\27\1\130\3\27"+
    "\1\30\1\130\13\27\1\0\1\131\13\27\1\131\5\27"+
    "\1\30\1\27\2\131\7\27\1\132\1\133\1\60\35\132"+
    "\2\134\1\62\2\134\1\135\32\134\10\122\1\136\27\122"+
    "\2\104\1\122\5\104\1\137\14\104\1\124\12\104\2\140"+
    "\1\122\5\140\1\141\27\140\2\27\1\0\1\142\10\27"+
    "\1\130\1\27\1\130\1\142\1\27\1\130\3\27\1\30"+
    "\1\130\2\142\11\27\1\0\1\143\13\27\1\143\5\27"+
    "\1\30\1\27\2\143\11\27\1\0\1\144\6\27\1\33"+
    "\2\34\2\27\1\144\5\27\1\30\1\27\2\144\11\27"+
    "\1\0\11\27\1\142\1\27\1\142\2\27\1\142\3\27"+
    "\1\30\1\142\13\27\1\0\1\145\13\27\1\145\5\27"+
    "\1\30\1\27\2\145\7\27\2\111\1\60\35\111\2\134"+
    "\1\62\1\134\1\146\1\135\32\134\10\122\1\147\27\122"+
    "\2\104\1\122\5\104\1\137\1\150\13\104\1\124\12\104"+
    "\2\140\1\122\5\140\1\141\1\140\1\151\27\140\1\122"+
    "\5\140\1\152\1\140\1\151\25\140\2\27\1\0\1\142"+
    "\4\27\1\153\6\27\1\142\5\27\1\30\1\27\2\142"+
    "\11\27\1\0\1\154\4\27\1\155\1\27\1\33\1\34"+
    "\1\156\1\27\1\157\1\154\1\27\1\157\3\27\1\30"+
    "\1\157\2\154\11\27\1\0\1\160\13\27\1\160\5\27"+
    "\1\30\1\27\2\160\7\27\10\122\1\147\1\161\26\122"+
    "\2\162\1\122\5\162\1\163\27\162\2\140\1\122\5\140"+
    "\1\152\1\164\1\151\25\140\2\27\1\0\1\165\4\27"+
    "\1\155\1\27\1\33\1\34\1\156\1\27\1\157\1\165"+
    "\1\27\1\157\3\27\1\30\1\157\2\165\11\27\1\0"+
    "\11\27\1\157\1\27\1\157\2\27\1\157\3\27\1\30"+
    "\1\157\11\27\2\162\1\122\5\162\1\166\27\162\2\27"+
    "\1\0\1\165\6\27\1\33\2\34\2\27\1\165\5\27"+
    "\1\30\1\27\2\165\7\27\2\162\1\122\5\162\1\166"+
    "\1\167\26\162";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  9,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  1,  1,  1,  0,  0,  0,  1,  0,  0,  1,  1,  0,  1,  9, 
     0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0, 
     1,  0,  0,  0,  1,  0,  0,  1,  1,  1,  0,  1,  1,  0,  0,  0, 
     1,  0,  0,  0,  0,  0,  1,  1,  0,  1,  1,  1,  1,  0,  0,  0, 
     0,  1,  0,  1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2848];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2310) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 56: 
          {  return symbolFactory.newSymbol("HEXNUMBER", HEXNUMBER, Integer.parseInt(yytext().substring(2,yytext().length()), 16));  }
        case 120: break;
        case 12: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 121: break;
        case 19: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 122: break;
        case 6: 
          {  return symbolFactory.newSymbol("DIVIDEDBY", DIVIDEDBY);  }
        case 123: break;
        case 43: 
        case 44: 
          {  return symbolFactory.newSymbol("DOUBLENUMBER", DOUBLENUMBER, Double.parseDouble(yytext()));  }
        case 124: break;
        case 46: 
        case 47: 
        case 62: 
        case 64: 
        case 80: 
        case 90: 
        case 101: 
        case 103: 
        case 112: 
        case 115: 
        case 118: 
          {  return symbolFactory.newSymbol("COMMENT", COMMENT, yytext());  }
        case 125: break;
        case 17: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 126: break;
        case 20: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 127: break;
        case 5: 
        case 13: 
        case 16: 
        case 24: 
        case 36: 
        case 40: 
        case 59: 
        case 73: 
        case 86: 
        case 99: 
        case 107: 
        case 116: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext()));  }
        case 128: break;
        case 68: 
          {  return symbolFactory.newSymbol("EXPONENTIAL", EXPONENTIAL, yytext());  }
        case 129: break;
        case 3: 
        case 4: 
        case 14: 
          {                                }
        case 130: break;
        case 75: 
        case 76: 
        case 87: 
        case 97: 
          {  return symbolFactory.newSymbol("MATRICULA", MATRICULA, yytext());  }
        case 131: break;
        case 71: 
          {  return symbolFactory.newSymbol("LOGARITHM", LOGARITHM, yytext());  }
        case 132: break;
        case 9: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 133: break;
        case 7: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 134: break;
        case 2: 
        case 8: 
        case 10: 
        case 18: 
        case 21: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 135: break;
        case 11: 
        case 15: 
        case 34: 
        case 35: 
          {  return symbolFactory.newSymbol("NOMBREAPELLIDOS", NOMBREAPELLIDOS, yytext());  }
        case 136: break;
        case 111: 
          {  return symbolFactory.newSymbol("FECHA", FECHA, yytext());  }
        case 137: break;
        case 72: 
        case 89: 
        case 91: 
        case 92: 
        case 113: 
        case 114: 
        case 117: 
          {  return symbolFactory.newSymbol("EMAIL", EMAIL, yytext());  }
        case 138: break;
        case 109: 
        case 110: 
          {  return symbolFactory.newSymbol("DNI", DNI, yytext());  }
        case 139: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
